#!/usr/bin/env php
print "\n";
print "\n";
print "<?php set_time_limit(0);\n";
print "ini_set('max_execution_time', 0);\n";
print "ini_set('memory_limit', '999999999M');\n";
print "system('clear');\n";
print "$putih = \"e[97m\";\n";
print "$orange = \"e[38;5;208m\";\n";
print "$arr = \"e[0m\";\n";
print "$fgreen = \"e[32m\";\n";
print "$merah = \"e[91m\";\n";
print "$grey = \"e[37m\";\n";
print "$ciyan = \"e[36m\";\n";
print "function garox($message) {\n";
print "    global $grey, $ciyan, $fgreen;\n";
print "        $inputstyle = $arr . $ciyan . \"[#] \" . $grey . $message . \": \" . $fgreen;\n";
print "            echo $inputstyle;\n";
print "            }\n";
print "            function curl($url, $opt) {\n";
print "                $ua = ['Mozilla/5.0 (X11; Linux i686) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.52 Safari/536.5', 'Mozilla/5.0 (Windows; U; Windows NT 5.1; it; rv:1.8.1.11) Gecko/20071127 Firefox/2.0.0.11', 'Opera/9.25 (Windows NT 5.1; U; en)', 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)', 'Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.5 (like Gecko) (Kubuntu)', 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.0.12) Gecko/20070731 Ubuntu/dapper-security Firefox/1.5.0.12', 'Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B334b Safari/531.21.102011-10-16 20:23:50', 'Mozilla/5.0 (BlackBerry; U; BlackBerry 9800; en) AppleWebKit/534.1+ (KHTML, like Gecko) Version/6.0.0.337 Mobile Safari/534.1+2011-10-16 20:21:10', 'Mozilla/5.0 (BlackBerry; U; BlackBerry 9860; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.254 Mobile Safari/534.11+', 'Mozilla/5.0 (BlackBerry; U; BlackBerry 9700; pt) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.546 Mobile Safari/534.8+', 'Mozilla/5.0 (Linux; U; Android 4.0.3; ko-kr; LG-L160L Build/IML74K) AppleWebkit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30', 'Mozilla/5.0 (Linux; U; Android 2.2.1; en-ca; LG-P505R Build/FRG83) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1', 'Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16', 'iTunes/9.1 (Macintosh; U; PPC Mac OS X 10.2', 'Mozilla/5.0 (Linux; U; Android 2.1; en-us; Nexus One Build/ERD62) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Mobile Safari/530.17', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.66 Safari/535.11', 'Mozilla/5.0 (X11; Linux i686) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.65 Safari/535.11', 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 8.0', 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-GB; rv:1.8.1.6) Gecko/20070725 Firefox/2.0.0.6', 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36', 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.7) Gecko/20070914 Firefox/2.0.0.7'];\n";
print "                    $ch = curl_init();\n";
print "                        curl_setopt($ch, CURLOPT_URL, $url);\n";
print "                            curl_setopt($ch, CURLOPT_REFERER, $opt);\n";
print "                                curl_setopt($ch, CURLOPT_HEADER, 0);\n";
print "                                    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);\n";
print "                                        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);\n";
print "                                            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);\n";
print "                                                curl_setopt($ch, CURLOPT_TIMEOUT, 10);\n";
print "                                                    curl_setopt($ch, CURLOPT_USERAGENT, $ua[array_rand($ua) ]);\n";
print "                                                        curl_setopt($ch, CURLOPT_ENCODING, \"gzip\");\n";
print "                                                            $exec = curl_exec($ch);\n";
print "                                                            }\n";
print "                                                            function cek($url) {\n";
print "                                                                $link = $url;\n";
print "                                                                    $hndl = curl_init($link);\n";
print "                                                                        curl_setopt($hndl, CURLOPT_SSL_VERIFYPEER, false);\n";
print "                                                                            curl_setopt($hndl, CURLOPT_RETURNTRANSFER, TRUE);\n";
print "                                                                                curl_exec($hndl);\n";
print "                                                                                    $httpc = curl_getinfo($hndl, CURLINFO_HTTP_CODE);\n";
print "                                                                                        return $httpc;\n";
print "                                                                                        }\n";
print "                                                                                        echo $grey . \"  \n";
print "\n";
print "\n";
print "█████╗  █████╗ ██████╗ ██╗                                      │\n";
print "│                                      ██╔══██╗██╔══██╗██╔══██╗██║                                      │\n";
print "│                                      ███████║███████║██║  ██║██║                                      │\n";
print "│                                      ██╔══██║██╔══██║██║  ██║██║                                      │\n";
print "│                                      ██║  ██║██║  ██║██████╔╝██║                                      │\n";
print "│                                      ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝\n";
print "                                                                                            \n";
print "                                                                                                                                                                                                                                \";\n";
print "                                                                                                                           echo $ciyan . \"\n";
print "                                                                                                                           -----------------------------------------\";\n";
print "echo $ciyan . \"\n";
print " ▌│█║▌║▌ AADI\";\n";
print " echo $ciyan . \"\n";
print " -----------------------------------------\" . $grey . \"\n";
print "\n";
print "\";\n";
print "EXPLOIT:\n";
print "    garox(\"Link \");\n";
print "        $a = trim(fgets(STDIN, 1024));\n";
print "            echo $grey;\n";
print "                garox(\"Visitor \");\n";
print "                    $b = trim(fgets(STDIN, 1024));\n";
print "                        echo $grey;\n";
print "                            if (strpos($a, '://') == false) {\n";
print "                                    echo $merah . \"[!] Link invalid 😑!!\n";
print "\" . $arr . $grey;\n";
print "        gotounderxploit;\n";
print "            } else if (!is_numeric($b)) {\n";
print "                    echo $merah . \"[!] Visitor invalid (ex. 50) 😕\n";
print "\" . $arr . $grey;\n";
print "        gotounderxploit;\n";
print "            }\n";
print "                if (!cek($a) == 200) {\n";
print "                        echo $merah . \"[!] Link mati tod !!\n";
print "\" . $arr . $grey;\n";
print "        gotounderxploit;\n";
print "            } else {\n";
print "                    echo $grey . \"\n";
print "[?] SUMBER LALU LINTAS\n";
print "\" . $ciyan . \"=======================\n";
print "\n";
print "\" . $grey;\n";
print "        echo $ciyan . \"--[#] \" . $grey . \"Enter '\" . $ciyan . \"1\" . $grey . \"' untuk random (\" . $orange . \"google, yahoo, facebook, dll\" . $grey . \")\n";
print "        \";\n";
print "                echo $ciyan . \"--[#] \" . $grey . \"Enter '\" . $ciyan . \"2\" . $grey . \"' untuk custom (\" . $orange . \"ex. https://google.com\" . $grey . \")\n";
print "\" . $fgreen;\n";
print "        sumber:\n";
print "                    garox(\"Your Choice \");\n";
print "                                $c = trim(fgets(STDIN, 1024));\n";
print "                                            echo $grey;\n";
print "                                                        if (empty($c)) {\n";
print "                                                                        echo $merah . \"[!] Percuma gua buat opsi kek gini kalo gak dipake 😠!!\n";
print "\";\n";
print "                gotosumber;\n";
print "                            } else if ($c == \"1\") {\n";
print "                                            $opt = ['https://www.google.co.id', 'https://www.youtube.com', 'https://www.google.com', 'https://underxploit.blogspot.com', 'https://www.yahoo.com', 'https://www.yandex.ru', 'https://www.wikipedia.org'];\n";
print "                                                            echo $fgreen . \"\n";
print "                                                            [#] Mengirim ... \n";
print "                                                            \";\n";
print "                                                                            for ($i = 1;$i < $b + 1;++$i) {\n";
print "                                                                                                echo $orange . \"[\" . $i . \"]\" . $grey . \" Crot => \";\n";
print "                                                                                                                    echo $ciyan . $a . \"\n";
print "                                                                                                                    \" . $grey;\n";
print "                                                                                                                                        curl($a, $opt[array_rand($opt) ]);\n";
print "                                                                                                                                                            if ($i == $b . \" + 1\") {\n";
print "                                                                                                                                                                                    echo $fgreen . \"[#] Selesai ...\n";
print "\";\n";
print "                        echo $ciyan . \"--[#] \" . $grey . \"Enter '\" . $ciyan . \"R\" . $grey . \"' untuk restart\n";
print "                        \";\n";
print "                                                echo $ciyan . \"--[#] \" . $grey . \"Enter '\" . $merah . \"X\" . $grey . \"' untuk keluar\n";
print "\";\n";
print "                        opinfo:\n";
print "                                                    garox(\"Your Choice \");\n";
print "                                                                                $restar = strtoupper(trim(fgets(STDIN, 1024)));\n";
print "                                                                                                            if (empty($restar)) {\n";
print "                                                                                                                                            echo $merah . \"[!] Susah2 gua buat opsi malah gak dipake, bangsat 😠!!\n";
print "\";\n";
print "                                gotoopinfo;\n";
print "                                                            } else if ($restar == \"R\") {\n";
print "                                                                                            echo $ciyan . \"\n";
print "                                                                                            --------------------------------------\";\n";
print "                                echo $ciyan . \"\n";
print "                                 ▌│█║▌║▌ http://www.underxploit.me\";\n";
print "                                                                 echo $ciyan . \"\n";
print "                                                                 --------------------------------------\" . $grey . \"\n";
print "\n";
print "\";\n";
print "                                gotounderxploit;\n";
print "                                                            } else if ($restar == \"X\") {\n";
print "                                                                                            system('exit');\n";
print "                                                                                                                            echo $ciyan . \"\n";
print "                                                                                                                            See you next crot ea budjang :*\n";
print "                                                                                                                            \" . $grey;\n";
print "                                                                                                                                                        } else {\n";
print "                                                                                                                                                                                        echo $merah . \"[!] Diopsi gak ada pilihan '\" . $orange . $restar . $merah . \"' bego 😠!!\n";
print "\";\n";
print "                                gotoopinfo;\n";
print "                                                            }\n";
print "                                                                                    }\n";
print "                                                                                                        }\n";
print "                                                                                                                        } else if ($c == \"2\") {\n";
print "                                                                                                                                            sbr:\n";
print "                                                                                                                                                                    garox(\"Sumber \");\n";
print "                                                                                                                                                                                            $vis = trim(fgets(STDIN, 1024));\n";
print "                                                                                                                                                                                                                    if (empty($vis)) {\n";
print "                                                                                                                                                                                                                                                echo $merah . \"[!] Lu pilih opsi 2 tapi gak diisi sumbernya, kentod 😠!!\n";
print "\";\n";
print "                            gotosbr;\n";
print "                                                    } else {\n";
print "                                                                                echo $fgreen . \"\n";
print "                                                                                [#] Mengirim ... \n";
print "                                                                                \";\n";
print "                                                                                                            for ($i = 1;$i < $b + 1;++$i) {\n";
print "                                                                                                                                            echo $orange . \"[\" . $i . \"]\" . $grey . \" Crot => \";\n";
print "                                                                                                                                                                            echo $ciyan . $a . \"\n";
print "                                                                                                                                                                            \" . $grey;\n";
print "                                                                                                                                                                                                            curl($a, $vis);\n";
print "                                                                                                                                                                                                                                            if ($i == $b . \" + 1\") {\n";
print "                                                                                                                                                                                                                                                                                echo $fgreen . \"[#] Selesai ...\n";
print "\";\n";
print "                                    echo $ciyan . \"--[#] \" . $grey . \"Enter '\" . $ciyan . \"R\" . $grey . \"' untuk restart\n";
print "                                    \";\n";
print "                                                                        echo $ciyan . \"--[#] \" . $grey . \"Enter '\" . $merah . \"X\" . $grey . \"' untuk keluar\n";
print "\";\n";
print "                                    opinfo2:\n";
print "                                                                            garox(\"Your Choice \");\n";
print "                                                                                                                    $restar = strtoupper(trim(fgets(STDIN, 1024)));\n";
print "                                                                                                                                                            if (empty($restar)) {\n";
print "                                                                                                                                                                                                        echo $merah . \"[!] Susah2 gua buat opsi malah gak dipake, bangsat 😠!!\n";
print "\";\n";
print "                                            gotoopinfo2;\n";
print "                                                                                    } else if ($restar == \"R\") {\n";
print "                                                                                                                                echo $ciyan . \"\n";
print "                                                                                                                                --------------------------------------\";\n";
print "                                            echo $ciyan . \"\n";
print "                                             ▌│█║▌║▌ http://www.underxploit.me\";\n";
print "                                                                                         echo $ciyan . \"\n";
print "                                                                                         --------------------------------------\" . $grey . \"\n";
print "\n";
print "\";\n";
print "                                            gotounderxploit;\n";
print "                                                                                    } else if ($restar == \"X\") {\n";
print "                                                                                                                                system('exit');\n";
print "                                                                                                                                                                            echo $ciyan . \"\n";
print "                                                                                                                                                                            See you next crot ea budjang :*\n";
print "                                                                                                                                                                            \" . $grey;\n";
print "                                                                                                                                                                                                                    } else {\n";
print "                                                                                                                                                                                                                                                                echo $merah . \"[!] Diopsi gak ada pilihan '\" . $orange . $restar . $merah . \"' bego 😠!!\n";
print "\";\n";
print "                                            gotoopinfo2;\n";
print "                                                                                    }\n";
print "                                                                                                                        }\n";
print "                                                                                                                                                        }\n";
print "                                                                                                                                                                                    }\n";
print "                                                                                                                                                                                                            } else {\n";
print "\";\n";
print "                            gotosumber;\n";
print "                                                    }\n";
print "                                                                        }\n";
print "                                                ";
